application_web/application_web/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
]

application_web/my_app/urls.py
from django.urls import path

from . import views

app_name = 'my_app'

urlpatterns = [
    path('index', views.index, name='index'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

application_web/my_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    owner = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + "..."

application_web/my_app/views.py
from django.shortcuts import render
from .models import Topic
from django.contrib.auth.decorators import login_required
from django.http import Http404


@login_required
def index(request):
    topics = Topic.objects.filter(owner=request.user).order_by('-date_added')
    context = {
        'topics': topics,
    }
    return render(request,
                  'index.html', context)


@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {
        'topic': topic,
        'entries': entries,
    }
    return render(request,
                  'topic.html', context)

application_web/my_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Изучаем Django</title>
	<link rel="stylesheet" type="text/css" href="{% static 'my_app/style.css' %}">
</head>
<body>
<div class="header">
	<p><a href="{% url 'my_app:index' %}">
	Журнал записей пользователя
	{% if user.is_authenticated %}{{ user.username }}{% endif %}
	</a></p>
</div>

{% block content %}{% endblock content %}

</body>
</html>

application_web/my_app/templates/index.html
{% extends 'base.html' %}
 
{% block content %}
 
  <h3>Темы:</h3>

  {% for topic in topics %}
    <p>
      <strong>
        <a href="topics/{{ topic.id }}/">
          {{topic.text}}
        </a>
      </strong>
      (Дата создания: {{topic.date_added|date:'H:i d/m/Y'}})
    </p>
  {% empty %}
    <p>Пока нет тем</p>
  {% endfor %}
<div class="timetable-page">
    <div class="timetable-container">
        <div class="timetable-box">
<img alt="timetable" src="https://e7.pngegg.com/pngimages/603/31/png-clipart-paper-drawing-pencil-pencil-pencil-text.png" width="700">
    </div>
    </div>
</div>
{% endblock content %}

application_web/my_app/templates/topic.html
{% extends 'base.html' %}
 
{% block content %}
 
	<h3>Тема: {{topic}}</h3>
 
	{% for entry in entries %}
		<p>
			{{entry.text|linebreaks}}
			(Дата создания: {{entry.date_added|date:'H:i d/m/Y'}})
		</p>
	{% empty %}
		<p>Пока нет записей</p>	
	{% endfor %}
 
{% endblock content %} 